#!/bin/bash

echo "$DIVIDER"
echo " Welcome to Hardening Manager!"

for file in $LIBFILES
do
    filebase=$(basename "$file")
    filename="${filebase%.*}"

    . "$file"

    echo "$DIVIDER"
    echo "#" "$($filename::name)"
    echo "#" "$($filename::description)"

#    tmpCommands=$($filename::help)
#    join "|" "${tmpCommands[@]}"

    tmpCommands=""
    for cmd in $("$filename::help")
    do
#        echo "- $filename $cmd"
        tmpCommands="$tmpCommands|$cmd"
    done;
    echo "* Usage: $filename {${tmpCommands:1}}"
done;
echo "$DIVIDER"
